### ISSUE TITLE
TypeError: object of type 'AntiGate' has no len()

### ISSUE THREAD

**Issue by oneumyvakin** [gotlium/antigate#10]
Let's add len() method.

Will be useful sometimes.

**Comment by gotlium** [comment]
explain what are you want.

**Comment by oneumyvakin** [comment]
````
from antigate import AntiGate

apikey = 'key'
captcha_file = 'test.png'
captcha_gate = AntiGate(apikey, captcha_file)

print(captcha_gate)
len(captcha_gate)  # this line generate following error
````
Traceback (most recent call last):
  File "anti.py", line 19, in <module>
    len(captcha_gate)
TypeError: object of type 'AntiGate' has no len()

**Comment by gotlium** [comment]
yes, because that is instance. you can use __str__:
````
from antigate import AntiGate

apikey = 'key'
captcha_file = 'test.png'
captcha_gate = AntiGate(apikey, captcha_file)

print(captcha_gate)
len(captcha_gate.__str__())
````

I can add __len__ method to class when I have a time. Or you can do it by your self, and send pull request.
