### ISSUE TITLE
Пидарасы сломали api

### ISSUE THREAD

**Issue by ololoe** [gotlium/antigate#11]
GET /res.php?action=get&id=204833069&key=<key> HTTP/1.1
User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/535.7 (KHTML, like Gecko) Chrome/16.0.912.36 Safari/535.7
Host: antigate.com
Accept-Encoding: gzip
Referer: http://antigate.com/res.php?action=get&id=204833069&key=<key>
Accept-Charset: utf-8,windows-1251;q=0.7,*;q=0.6
Accept-Language: en-us,en;q=0.6
Keep-Alive: 300
Accept: text/xml,application/xml,application/xhtml+xml,text/html;q=0.9,text/plain;q=0.8,image/png,*/*;q=0.3

HTTP/1.1 200 OK
Server: nginx/1.8.0
Date: Tue, 01 Sep 2015 06:06:02 GMT
Content-Type: text/html; charset=utf-8
Transfer-Encoding: chunked
Connection: keep-alive
X-Powered-By: PHP/5.4.43

f
OK|yberste also
0

00000DAD 2d 42 79 3a 20 50 48 50 2f 35 2e 34 2e 34 33 0d -By: PHP /5.4.43.
00000DBD 0a 0d 0a 66 0d 0a 4f 4b 7c 79 62 65 72 73 74 65 ...f..OK |yberste
00000DCD 20 61 6c 73 6f 0d 0a 30 0d 0a 0d 0a also..0 ....

Из-за переноса строк в ответе ничего не работает.

Что интересно

curl -i "http://antigate.com/res.php?action=get&id=204833069&key=<key>

работает. Поддержка говорит, что раз курл работает, то проблема на стороне библиотеки. На вопрос, что не так в запросе делает вид что не слышит.

Кстати, следовало бы не возвращать none, а кидать исключение.

**Comment by gotlium** [comment]
ну я как обычно могу лишь предложить пул реквест) сейчас в мастере новые изменения, которых нет еще на pypi. и стоит я думаю сначала попробовать тесты локально прогнать, что бы подтвердить работоспособность.

**Comment by ololoe** [comment]
Прогоняй и выкладывай.

**Comment by gotlium** [comment]
в данный момент нет такой возможности

**Comment by ololoe** [comment]
Эт почему? Ты же автор модуля на pypi?

Млять, проблема таки в модуле.
    
    # так работает
    captcha = antigate.AntiGate(api_key, filename)

    # а так нет
    ant = antigate.AntiGate(api_key)
    captcha = ant.run(filename)

Что не отменяет того, что проблема на стороне сервера и раньше все работало.

**Comment by gotlium** [comment]
дело не в том кто автор, а в том что есть у человека время или нет. 
мат здесь - не уместен и не является хорошим тоном.
тут не увидил никаких подробностей. используется то что на pypi или мастер? 
тесты мастера пройдены без проблем.
если имеется конкретная проблема и есть возможность решить ее самостоятельно,
то логичнее сделать и просто отправить пул реквест. это opensource и никто никому не должен.

    # make test 
    python test_cases.py
    No handlers could be found for logger "antigate"
    .............
    ----------------------------------------------------------------------
    Ran 13 tests in 242.081s

    OK

**Comment by gotlium** [comment]
так и не должно работать:

    # а так нет
    ant = antigate.AntiGate(api_key)
    captcha = ant.run(filename)

а вот так должно:

    ant = antigate.AntiGate(api_key, auto_run=False)
    ant.run(filename)
    captcha = ant.__str__()

надо читать код и вникать. как минимум все это описано в README и примеры есть в тестах.

вот так было бы правильнее:

    gate = AntiGate('API-KEY', auto_run=False)
    captcha_id = gate.send('captcha1.jpg')
    print gate.get(captcha_id)

**Comment by ololoe** [comment]
Я не знал, что на то, чтобы отравить код с гитхаба на pypi нужно время, а на то чтобы писать в коментах - нет.

Мат был из-за того, что как только мне понадобились капчи и закинул деньги - тут же все сломалось.

> если имеется конкретная проблема и есть возможность решить ее самостоятельно,
то логичнее сделать

Пожалуй, так и сделаю. Тем, кто наступил на те же грабли - осторожно, модуль глючный! Делайте как в примерах, везде разложены грабли!

>а вот так должно:

    ant = antigate.AntiGate(api_key, auto_run=False)
    ant.run(filename)
    captcha = ant.__str__()

Ну это вообще пушка. Какой смысл имеет auto_run=True без файла? Что он за авторан запускает?

     captcha = ant.__str__()
Так не делают же.

> надо читать код и вникать. 

Слушай, за лишние полчаса я перепишу модуль с нормальной обработкой ошибок и нормальным api. Я этого не делал потому что не нужно было.

Баг api все это не отменяет, на клиента по прежнему приходят лишние переносы строки. **Но каким-то фигом модуль их хавает в одном случае и не хавает в другом**

**Comment by gotlium** [comment]
еще раз повторюсь - это opensource. не нравится - не используйте. 
прежде чем кого-то обвинять - читайте внимательно код, не будте голословным, и не задавайте глупых вопросов.
наберитесь опыта. не хотите готовое - пишите свое.

**Comment by ololoe** [comment]
> наберитесь опыта.

Ахуеть. **Ты** это **мне**? Научить сначала апи писать, которым можно пользоваться и не бояться наступить на мину.

**Comment by gotlium** [comment]
с вами нет более смысла продолжать разгов. поучись манерам, школота.

**Comment by ololoe** [comment]
Мудачок, чини детектор.
