### ISSUE TITLE
How to correctly pass is_russian?

### ISSUE THREAD

**Issue by vavoluk** [gotlium/antigate#12]
I had an error with is_russian:
```
grab.error.GrabMisuseError: Unknown option: is_russian
```

How to correctly pass is_russian?

**Comment by gotlium** [comment]
>>> from antigate import AntiGate
    >>> config = {'min_len': '3', 'max_len': '5', 'phrase': '2', 'is_russian': '1'}
    >>> gate = AntiGate('API-KEY', 'captcha.jpg', send_config=config)
