### ISSUE TITLE
grab.error.GrabInvalidUrl: decode() takes no keyword arguments

### ISSUE THREAD

**Issue by pgamaster** [gotlium/antigate#13]
Simple script:
#!/usr/bin/python
# -*- coding: utf-8 -*-

from antigate import AntiGate
gate = AntiGate('my-api-key')
print gate.balance()

Gets this error:
grab.error.GrabInvalidUrl: decode() takes no keyword arguments: http://antigate.com/res.php?action=getbalance&key=my-api-key

Centos 6.5, Python 2.6
x86_64 x86_64 x86_64 GNU/Linux

Could you help please?

**Comment by gotlium** [comment]
which version of anti gate is used?

**Comment by pgamaster** [comment]
antigate-1.3.4

**Comment by gotlium** [comment]
# mkvirtualenv antigate-test
...

(antigate-test)gotlium@::o) antigate (master)# pip install antigate==1.3.4
...

(antigate-test)gotlium@::o) antigate (master)# ipython

In [1]: from antigate import AntiGate

In [2]: gate = AntiGate('...')

In [3]: gate.balance()
Out[3]: 0.775

I think grab lib not support Python 2.6 at this moment. Update your python installation to 2.7 or 3.4

**Comment by pgamaster** [comment]
Python 2.7 worked thanks :)
