### ISSUE TITLE
Убрать из зависимостей Grab

### ISSUE THREAD

**Issue by egorsmkv** [gotlium/antigate#14]
Он тяжеловесен и часто только мешает. Можно переписать всё с requests?

**Comment by gotlium** [comment]
Я не против. Вы можете написать несколько бекендов для работы с requests, urllib и тд, и прислать пул реквест) Главное что бы не сломалось то что уже есть, и была обратная совместимость. В данный момент у меня нет возможности заниматься этим.

**Comment by egorsmkv** [comment]
Спасибо!

**Comment by gotlium** [comment]
Np)
