### ISSUE TITLE
How can I solve reCAPTCHA?

### ISSUE THREAD

**Issue by lucastamoios** [gotlium/antigate#18]
How can I create tasks like `NoCaptchaTask` with this client and solve [reCAPTCHA](https://anticaptcha.atlassian.net/wiki/display/API/NoCaptchaTask+%3A+Google+Recaptcha+puzzle+solving) tests?

**Comment by gotlium** [comment]
Check `antigate` api! If it doesn't support `reCaptcha`, this battery could not help to solve your issue!
