### ISSUE TITLE
ERROR_NO_SUCH_METHOD

### ISSUE THREAD

**Issue by iamyeti** [gotlium/antigate#7]
ошибка на 92 строке:
```
{'key': self.key, 'file': UploadFile(filename)}, self.send_config))
```
не передаёт метод, который теперь требует antigate, правильно будет так:
```
{'method': 'post', 'key': self.key, 'file': UploadFile(filename)}, self.send_config))
```

**Comment by gotlium** [comment]
пришлите пожалуйста pull-request и добавьте в тесты новый метод для проверки работоспособности батарейки после фикса.

**Comment by gotlium** [comment]
так же возможно что вы что-то используете не так, так как по коду я вижу:

    self.g.setup(multipart_post=self._update_params(
                {'key': self.key, 'file': UploadFile(captcha_file)},
                self.send_config
    ))

здесь необходим файл и передается как multipart_post. файлы и буферы покрыты тестами.

**Comment by iamyeti** [comment]
это версия которая на гитабе(которая, кстати, тоже перестала работать по той же причине), а в версии с pip 92 строка такая:
{'key': self.key, 'file': UploadFile(filename)}, self.send_config))
как я понимаю, теперь нужно передавать названием метода:
{'method': 'post', 'key': self.key, 'file': UploadFile(filename)}, self.send_config))

**Comment by gotlium** [comment]
то есть по сути это проблема grab?

**Comment by iamyeti** [comment]
почему? мне кажется просто antigate стал требовать название метода. antigate перестал работать из-за ошибки ERROR_NO_SUCH_METHOD.
```
Traceback (most recent call last):
File "***", line 92, in 
go()
File "C:Developmentavito-regerreger.py", line 72, in go
cptch = AntiGate(antigate_key, captcha_name, send_config=config)
File "C:Python27libsite-packagesantigate__init__.py", line 41, in __init_
self.run(filename)
File "C:Python27libsite-packagesantigate__init__.py", line 156, in run
self.send(filename)
File "C:Python27libsite-packagesantigate__init__.py", line 105, in send
raise AntiGateError(msg)
antigate.AntiGateError: ERROR_NO_SUCH_METHOD
```

**Comment by gotlium** [comment]
выходит что были какие-то изменения в апи, и требуется дополнительный параметр

**Comment by gotlium** [comment]
спасибо за репорт. поправил этот момент.
