### ISSUE TITLE
body.decode()

### ISSUE THREAD

**Issue by divanovGH** [gotlium/antigate#8]
In antigate.AntiGate._body must be self.g.response.body.decode().split('|'), not self.g.response.body.split('|')

**Comment by gotlium** [comment]
why?

**Comment by divanovGH** [comment]
it's need to work with python 3

**Comment by gotlium** [comment]
maybe you want send pull request?

**Comment by gotlium** [comment]
fixed on #9  . now all api opportunities is working properly
